final Map<String, List<Map<String, dynamic>>> itemsData = {
  "Fruits": [
    {
      "name": "Apple",
      "image": "images/apple.jpg",
      "price": 240,
      "discount": 10,
      "quantity": "1 kg",
      "rating": 4.5,
      "buyers": 220,
    },
    {
      "name": "Banana",
      "image": "images/banana.jpg",
      "price": 60,
      "discount": 5,
      "quantity": "1 dozen",
      "rating": 4.3,
      "buyers": 180,
    },
    {
      "name": "Mango",
      "image": "images/mango.jpg",
      "price": 70,
      "discount": 15,
      "quantity": "1 kg",
      "rating": 4.6,
      "buyers": 300,
    },
    {
      "name": "Orange",
      "image": "images/oranges.jpg",
      "price": 160,
      "discount": 8,
      "quantity": "1 kg",
      "rating": 4.2,
      "buyers": 145,
    },
    {
      "name": "Pomegranate",
      "image": "images/pomegranate.jpg",
      "price": 200,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.1,
      "buyers": 100,
    },
    {
      "name": "Guava",
      "image": "images/guava.jpg",
      "price": 50,
      "discount": 10,
      "quantity": "1 kg",
      "rating": 4.4,
      "buyers": 120,
    },
    {
      "name": "Grapes",
      "image": "images/grapes.jpg",
      "price": 35,
      "discount": 12,
      "quantity": "500 g",
      "rating": 4.3,
      "buyers": 210,
    },
    {
      "name": "Watermelon",
      "image": "images/watermelon.jpg",
      "price": 40,
      "discount": 5,
      "quantity": "1 pc",
      "rating": 4.0,
      "buyers": 85,
    },
  ],
  "Vegetables": [
    {
      "name": "Tomato",
      "image": "images/tomato.jpg",
      "price": 20,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.1,
      "buyers": 230,
    },
    {
      "name": "Potato",
      "image": "images/potato.jpg",
      "price": 25,
      "discount": 4,
      "quantity": "1 kg",
      "rating": 4.0,
      "buyers": 210,
    },
    {
      "name": "Onion",
      "image": "images/onion.jpg",
      "price": 30,
      "discount": 6,
      "quantity": "1 kg",
      "rating": 4.2,
      "buyers": 250,
    },
    {
      "name": "Carrot",
      "image": "images/carrot.jpg",
      "price": 40,
      "discount": 7,
      "quantity": "1 kg",
      "rating": 4.3,
      "buyers": 170,
    },
    {
      "name": "Cabbage",
      "image": "images/cabbage.jpg",
      "price": 25,
      "discount": 5,
      "quantity": "1 pc",
      "rating": 4.1,
      "buyers": 150,
    },
    {
      "name": "Ginger",
      "image": "images/ginger.jpg",
      "price": 60,
      "discount": 6,
      "quantity": "500 g",
      "rating": 4.2,
      "buyers": 140,
    },
    {
      "name": "Chilli",
      "image": "images/chilli.jpg",
      "price": 20,
      "discount": 5,
      "quantity": "500 g",
      "rating": 4.3,
      "buyers": 135,
    },
    {
      "name": "Brinjal",
      "image": "images/brinjal.jpg",
      "price": 30,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.0,
      "buyers": 125,
    },
  ],
  "Beverages": [
    {
      "name": "Coca Cola",
      "image": "images/coca_cola.jpg",
      "price": 50,
      "discount": 5,
      "quantity": "1 lt",
      "rating": 4.5,
      "buyers": 320,
    },
    {
      "name": "Thums Up",
      "image": "images/thums_up.jpg",
      "price": 50,
      "discount": 4,
      "quantity": "1 lt",
      "rating": 4.4,
      "buyers": 300,
    },
    {
      "name": "Maaza",
      "image": "images/maaza.jpg",
      "price": 10,
      "discount": 6,
      "quantity": "1 pc",
      "rating": 4.3,
      "buyers": 280,
    },
    {
      "name": "Mountain Dew",
      "image": "images/mountain_dew.jpg",
      "price": 40,
      "discount": 5,
      "quantity": "1 pc",
      "rating": 4.2,
      "buyers": 210,
    },
    {
      "name": "Sprite",
      "image": "images/sprite.jpg",
      "price": 70,
      "discount": 6,
      "quantity": "1 lt",
      "rating": 4.3,
      "buyers": 295,
    },
    {
      "name": "Kinley Soda",
      "image": "images/soda.webp",
      "price": 20,
      "discount": 10,
      "quantity": "1 lt",
      "rating": 4.6,
      "buyers": 170,
    },
    {
      "name": "Limca",
      "image": "images/limca.webp",
      "price": 50,
      "discount": 5,
      "quantity": "750 ml",
      "rating": 4.2,
      "buyers": 180,
    },
    {
      "name": "Pulpy Orange",
      "image": "images/pulpy_orange.jpg",
      "price": 90,
      "discount": 4,
      "quantity": "1 lt",
      "rating": 4.1,
      "buyers": 190,
    },
  ],
  "Snacks": [
    {
      "name": "Lays",
      "image": "images/lays.jpg",
      "price": 10,
      "discount": 5,
      "quantity": "1 pc",
      "rating": 4.3,
      "buyers": 400,
    },
    {
      "name": "Kurkure",
      "image": "images/kurkure.jpg",
      "price": 10,
      "discount": 5,
      "quantity": "1 pc",
      "rating": 4.2,
      "buyers": 390,
    },
    {
      "name": "Bingo",
      "image": "images/bingo.jpg",
      "price": 10,
      "discount": 6,
      "quantity": "1 pc",
      "rating": 4.1,
      "buyers": 350,
    },
    {
      "name": "Pringles",
      "image": "images/pringles.jpg",
      "price": 40,
      "discount": 7,
      "quantity": "1 pc",
      "rating": 4.2,
      "buyers": 280,
    },
    {
      "name": "Oreo",
      "image": "images/oreo.jpg",
      "price": 10,
      "discount": 10,
      "quantity": "1 pc",
      "rating": 4.5,
      "buyers": 260,
    },
    {
      "name": "Dairy Milk",
      "image": "images/dairy_milk.jpg",
      "price": 10,
      "discount": 6,
      "quantity": "1 pc",
      "rating": 4.4,
      "buyers": 230,
    },
    {
      "name": "Hide and Seek",
      "image": "images/hide_and_seek.webp",
      "price": 30,
      "discount": 5,
      "quantity": "1 pc",
      "rating": 4.3,
      "buyers": 220,
    },
    {
      "name": "5Star",
      "image": "images/5star.jpg",
      "price": 10,
      "discount": 2,
      "quantity": "1 pc",
      "rating": 4.0,
      "buyers": 210,
    },
  ],
  "Staples": [
    {
      "name": "All Purpose Flour",
      "image": "images/all_purpose_flour.webp",
      "price": 40,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.1,
      "buyers": 230,
    },
    {
      "name": "Gram Flour",
      "image": "images/gram_flour.jpg",
      "price": 90,
      "discount": 4,
      "quantity": "1 kg",
      "rating": 4.0,
      "buyers": 210,
    },
    {
      "name": "Corn Flour",
      "image": "images/corn_flour.webp",
      "price": 50,
      "discount": 6,
      "quantity": "1 kg",
      "rating": 4.2,
      "buyers": 250,
    },
    {
      "name": "Salt",
      "image": "images/salt.jpg",
      "price": 30,
      "discount": 7,
      "quantity": "1 kg",
      "rating": 4.3,
      "buyers": 170,
    },
    {
      "name": "Sugar",
      "image": "images/sugar.jpg",
      "price": 50,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.1,
      "buyers": 150,
    },
    {
      "name": "Turmeric",
      "image": "images/turmeric.jpg",
      "price": 150,
      "discount": 6,
      "quantity": "500 g",
      "rating": 4.2,
      "buyers": 140,
    },
    {
      "name": "Chilli Powder",
      "image": "images/chilli_powder.jpg",
      "price": 200,
      "discount": 5,
      "quantity": "500 gm",
      "rating": 4.3,
      "buyers": 135,
    },
    {
      "name": "wheat",
      "image": "images/wheat.jpg",
      "price": 50,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.0,
      "buyers": 125,
    },
  ],
  "Dairy": [
    {
      "name": "Ghee",
      "image": "images/ghee.jpg",
      "price": 90,
      "discount": 5,
      "quantity": "100 gm",
      "rating": 4.5,
      "buyers": 320,
    },
    {
      "name": "Curd",
      "image": "images/curd.jpg",
      "price": 40,
      "discount": 4,
      "quantity": "450 ml",
      "rating": 4.4,
      "buyers": 300,
    },
    {
      "name": "Butter",
      "image": "images/butter.jpeg",
      "price": 60,
      "discount": 6,
      "quantity": "100 gm",
      "rating": 4.3,
      "buyers": 280,
    },
    {
      "name": "Butter Milk",
      "image": "images/buttermilk.webp",
      "price": 10,
      "discount": 5,
      "quantity": "120 ml",
      "rating": 4.2,
      "buyers": 210,
    },
    {
      "name": "Milk Cake",
      "image": "images/milk_cake.webp",
      "price": 260,
      "discount": 6,
      "quantity": "1 kg",
      "rating": 4.3,
      "buyers": 295,
    },
    {
      "name": "Lassi",
      "image": "images/lassi.png",
      "price": 10,
      "discount": 10,
      "quantity": "100 ml",
      "rating": 4.6,
      "buyers": 170,
    },
    {
      "name": "Paneer",
      "image": "images/paneer.jpg",
      "price": 80,
      "discount": 5,
      "quantity": "100 gm",
      "rating": 4.2,
      "buyers": 180,
    },
    {
      "name": "Badam Milk",
      "image": "images/badam_milk.png",
      "price": 25,
      "discount": 4,
      "quantity": "200 ml",
      "rating": 4.1,
      "buyers": 190,
    },
  ],
  "Meat": [
    {
      "name": "Chicken",
      "image": "images/chicken.jpg",
      "price": 250,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.3,
      "buyers": 400,
    },
    {
      "name": "Mutton",
      "image": "images/mutton.jpg",
      "price": 990,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.2,
      "buyers": 390,
    },
    {
      "name": "Eggs",
      "image": "images/eggs.jpg",
      "price": 70,
      "discount": 6,
      "quantity": "1 dozen",
      "rating": 4.1,
      "buyers": 350,
    },
    {
      "name": "Fish",
      "image": "images/fish.jpg",
      "price": 150,
      "discount": 7,
      "quantity": "1 kg",
      "rating": 4.2,
      "buyers": 280,
    },
    {
      "name": "Prawns",
      "image": "images/prawn.jpg",
      "price": 110,
      "discount": 10,
      "quantity": "1 kg",
      "rating": 4.5,
      "buyers": 260,
    },
    {
      "name": "Crab",
      "image": "images/crab.jpg",
      "price": 150,
      "discount": 6,
      "quantity": "1 kg",
      "rating": 4.4,
      "buyers": 230,
    },
    {
      "name": "Dried Fish",
      "image": "images/dry_fish.jpg",
      "price": 110,
      "discount": 5,
      "quantity": "100 gm",
      "rating": 4.3,
      "buyers": 220,
    },
    {
      "name": "Dried Prawns",
      "image": "images/dry_prawn.webp",
      "price": 70,
      "discount": 2,
      "quantity": "100 gm",
      "rating": 4.0,
      "buyers": 210,
    },
  ],
  "Personal Care": [
    {
      "name": "Santoor",
      "image": "images/santoor.jpg",
      "price": 40,
      "discount": 5,
      "quantity": "100 gm",
      "rating": 4.1,
      "buyers": 230,
    },
    {
      "name": "Cliniplus",
      "image": "images/cliniplus.webp",
      "price": 80,
      "discount": 4,
      "quantity": "1 pc",
      "rating": 4.0,
      "buyers": 210,
    },
    {
      "name": "Whisper",
      "image": "images/whisper.jpg",
      "price": 50,
      "discount": 6,
      "quantity": "1 pc",
      "rating": 4.2,
      "buyers": 250,
    },
    {
      "name": "Colgate",
      "image": "images/colgate.jpg",
      "price": 85,
      "discount": 7,
      "quantity": "1oo gm",
      "rating": 4.3,
      "buyers": 170,
    },
    {
      "name": "Ponds",
      "image": "images/ponds.jpg",
      "price": 125,
      "discount": 5,
      "quantity": "1 pc",
      "rating": 4.1,
      "buyers": 150,
    },
    {
      "name": "Fair and Lovely",
      "image": "images/fair_and_lovely.jpg",
      "price": 65,
      "discount": 6,
      "quantity": "1 pc",
      "rating": 4.2,
      "buyers": 140,
    },
    {
      "name": "Parachute",
      "image": "images/parachute.jpg",
      "price": 350,
      "discount": 5,
      "quantity": "500 ml",
      "rating": 4.3,
      "buyers": 135,
    },
    {
      "name": "Indica Easy",
      "image": "images/indica_easy.jpg",
      "price": 30,
      "discount": 5,
      "quantity": "15 ml",
      "rating": 4.0,
      "buyers": 125,
    },
  ],
  "Household Cares": [
    {
      "name": "Vimbar",
      "image": "images/vimbar.jpg",
      "price": 10,
      "discount": 5,
      "quantity": "100 gm",
      "rating": 4.5,
      "buyers": 320,
    },
    {
      "name": "Surf Excel",
      "image": "images/surfexcel.webp",
      "price": 170,
      "discount": 4,
      "quantity": "1 kg",
      "rating": 4.4,
      "buyers": 300,
    },
    {
      "name": "Comfort",
      "image": "images/comfort.jpg",
      "price": 130,
      "discount": 6,
      "quantity": "1 lt",
      "rating": 4.3,
      "buyers": 280,
    },
    {
      "name": "Lizol",
      "image": "images/lizol.jpg",
      "price": 120,
      "discount": 5,
      "quantity": "1 lt",
      "rating": 4.2,
      "buyers": 210,
    },
    {
      "name": "Harpic",
      "image": "images/harpic.jpg",
      "price": 125,
      "discount": 6,
      "quantity": "1 pc",
      "rating": 4.3,
      "buyers": 295,
    },
    {
      "name": "Odonil",
      "image": "images/odonil.jpg",
      "price": 240,
      "discount": 10,
      "quantity": "1 pc",
      "rating": 4.6,
      "buyers": 170,
    },
    {
      "name": "Nippo Batteries",
      "image": "images/nippo_batteries.jpg",
      "price": 180,
      "discount": 5,
      "quantity": "1 sheet",
      "rating": 4.2,
      "buyers": 180,
    },
    {
      "name": "Good Knight",
      "image": "images/good_knight.jpg",
      "price": 105,
      "discount": 4,
      "quantity": "1 pc",
      "rating": 4.1,
      "buyers": 190,
    },
  ],
  "Grains": [
    {
      "name": "Moongdal",
      "image": "images/moongdal.jpg",
      "price": 120,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.3,
      "buyers": 400,
    },
    {
      "name": "Toordal",
      "image": "images/toordal.jpg",
      "price": 110,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.2,
      "buyers": 390,
    },
    {
      "name": "Chickpeas",
      "image": "images/chickpea.jpg",
      "price": 80,
      "discount": 6,
      "quantity": "1 kg",
      "rating": 4.1,
      "buyers": 350,
    },
    {
      "name": "Peas",
      "image": "images/peas.jpg",
      "price": 110,
      "discount": 7,
      "quantity": "1 kg",
      "rating": 4.2,
      "buyers": 280,
    },
    {
      "name": "Soyabean",
      "image": "images/soyabean.jpg",
      "price": 130,
      "discount": 10,
      "quantity": "1 kg",
      "rating": 4.5,
      "buyers": 260,
    },
    {
      "name": "Rajma",
      "image": "images/rajma.jpg",
      "price": 160,
      "discount": 6,
      "quantity": "1 kg",
      "rating": 4.4,
      "buyers": 230,
    },
    {
      "name": "Uraddal",
      "image": "images/uraddal.jpg",
      "price": 120,
      "discount": 5,
      "quantity": "1 kg",
      "rating": 4.3,
      "buyers": 220,
    },
    {
      "name": "Peanuts",
      "image": "images/peanuts.jpg",
      "price": 140,
      "discount": 2,
      "quantity": "1 kg",
      "rating": 4.0,
      "buyers": 210,
    },
  ],
  // Add categories: "Dairy Meat", "Staples", "Grains", "Household Cares", "Personal Cares"
  // using your own image assets and structure similar to above
};
